// This file will be generated by Supabase CLI
// For now, using a placeholder structure
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: any;
        Insert: any;
        Update: any;
      };
      orders: {
        Row: any;
        Insert: any;
        Update: any;
      };
      milestones: {
        Row: any;
        Insert: any;
        Update: any;
      };
      milestone_logs: {
        Row: any;
        Insert: any;
        Update: any;
      };
      delay_requests: {
        Row: any;
        Insert: any;
        Update: any;
      };
      notifications: {
        Row: any;
        Insert: any;
        Update: any;
      };
      order_attachments: {
        Row: any;
        Insert: any;
        Update: any;
      };
    };
  };
};
